# Generated by Django 5.1.6 on 2025-02-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_name_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_ru',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='description_ru',
        ),
    ]
