# Generated by Django 5.1.6 on 2025-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_city_city_name_en_remove_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
