# Generated by Django 5.1.6 on 2025-02-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_city_city_name_en_city_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'stars')},
        ),
    ]
